### ISSUE TITLE
Bug: prettier-ignore causes the code to be deleted

### ISSUE THREAD

**Issue by richex-cn** [prettier/plugin-pug#292]
### Plugin Version

v1.16.6

### Prettier Version

v2.4.1

### Which frameworks are affected?

- [ ] none
- [X] vue
- [ ] angular
- [ ] svelte

### Node Version

v14.9.0

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Prettier config

```json
// .prettierrc.js
module.exports = {
  tabWidth: 2,
  printWidth: 80,
  arrowParens: 'avoid',
  semi: false,
  singleQuote: true,
  proseWrap: 'always',
  requirePragma: false,
  bracketSpacing: true,
  trailingComma: 'none',
  jsxBracketSameLine: true,
  quoteProps: 'as-needed'
}
```

### Input

```pug
doctype html
head

body
  div
    .wrap
      // prettier-ignore
      img(src="1.jpg")/

    .list
      p hello world
```

### Output or Error

```bash
doctype html
head

body
  div
    .wrap
```

### Expected Output

```pug
doctype html
head

body
  div
    .wrap
      // prettier-ignore
      img(src="1.jpg")/

    .list
      p hello world
```

### Additional Context

This problem still exists in Vue files:

```
<template lang="pug">
div
  .wrap
    //- prettier-ignore
    img(src="1.jpg")/

  .list
    p hello world
</template>
```

Output:

```
<template lang="pug">
div
  .wrap
    </template>
```

**Comment by Shinigami92** [comment]
Sorry for late response, was in vacation for some days  

So first please always try to use `//-` comments instead of `//`, cause the later ones are rendered as regular html comments in the served website and the first one will get removed by pug by the transformation to html.

Also very interesting is your usage of `img(...)/`. Will look if the `/` at the end cause any issues :thinking: 

The code for the prettier-ignore processing is here:

https://github.com/prettier/plugin-pug/blob/bbd53b4ea06c19a71a06b3664f54e29d00946506/src/printer.ts#L1082-L1121

I will look into this the next few days and will use your examples in the TDD suite of the project (https://github.com/prettier/plugin-pug/tree/main/tests/prettier-ignore)

**Comment by richex-cn** [comment]
@Shinigami92 
Thank you for your response, I tried again `// prettier-ignore` or `//- prettier-ignore` and the optional `/` at the end of img, Unfortunately, I tried all possible combinations in html and vue files, and they all have the first problem. This should be a BUG, I am trying to find out the cause of the problem.

**Comment by Shinigami92** [comment]
Seems I fixed it :slightly_smiling_face: 

But...
1. I would like to have @lehni a review, cause it was his code :slightly_smiling_face: 
2. Do you have a more complex example with some nested `indent`/`outdent`?  
   If you look into my fix, you can see that it was an issue with incorrectly calculated `outdent`-level. So it could be that it works now for your simple case, but break again for more complex case :thinking:

**Comment by richex-cn** [comment]
Awesome! I successfully got the desired result in the pug file! But the problem still exists when using Vetur to format the vue file in VS Code. I still need some time to get familiar with the source code of Vetur. I am very sorry that I may not be able to follow up immediately due to work reasons.

**Comment by Shinigami92** [comment]
@richex-cn I assume you have tested it out via local changes of your `node_modules` content?
If so, could be that you need to fully reload VSCode after the changes due to caching mechanisms.
The Vetur extensions then re-reads the plugin. Otherwise I would assume that Vetur has it's own instance of my plugin and therefore while I haven't release this fix yet, it can also not apply it 🤷

So please wait for the release of `1.16.7` or higher.

**Comment by richex-cn** [comment]
@Shinigami92 Yeah, I pulled the repaired code and packaged and overwritten the files in `node_modules/@prettier/plugin-pug`, and then restarted VSCode. It works fine in the pug file, but there are still problems in the vue file. I reinstalled the dependencies after the new version was released, but it still works like this.
This should be related to the vetur extension, so I submitted an Issue and hope to get help: https://github.com/vuejs/vetur/issues/3165
